package entity;

public enum AcademicGrade {
    ASSOCIATE,
    UNINTERRUPTED_BACHELOR,
    INTERRUPTED_BACHELOR,
    UNINTERRUPTED_MASTERS,
    INTERRUPTED_MASTERS,
    UNINTERRUPTED_DOCTORATE,
    INTERRUPTED_DOCTORATE,
    PROFESSIONAL_DOCTORATE

}
